name: Submit release to the WinGet community repository

on:
  release:
    types: [published]

jobs:
  publish-winget:
    name: Submit to WinGet repository

    # winget-create is only supported on Windows
    runs-on: windows-latest

    # Only submit stable releases
    if: ${{ !github.event.release.prerelease }}

    # winget-create will read the following environment variable to access the GitHub token needed for submitting a PR
    # See https://aka.ms/winget-create-token
    env:
      WINGET_CREATE_GITHUB_TOKEN: ${{ secrets.WINGET_CREATE_GITHUB_TOKEN }}

    steps:
      - name: Submit package using wingetcreate
        run: |
          # Get installer info from release event
          $assets = '${{ toJSON(github.event.release.assets) }}' | ConvertFrom-Json
          $msixPackageUrl = $assets | Where-Object -Property name -like '*.msixbundle' | Select-Object -ExpandProperty browser_download_url
          $portablePackageUrl = $assets | Where-Object -Property name -eq 'wingetcreate.exe' | Select-Object -ExpandProperty browser_download_url
          $packageVersion = (${{ toJSON(github.event.release.tag_name) }}).Trim('v')

          # Update package using wingetcreate
          Invoke-WebRequest https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          .\wingetcreate.exe update Microsoft.WingetCreate `
            --version $packageVersion `
            --urls $msixPackageUrl "$portablePackageUrl|x64" "$portablePackageUrl|x86" `
            --submit
